version: '3'
services:
    jal_logger:
        build: ./jal_logger
        depends_on:
            - postgres
        volumes:
            - ./log/jal_logger:/var/log/cron

    postgres:
        image: postgres:alpine
        restart: always
        volumes:
            - ./postgres/init:/docker-entrypoint-initdb.d
            - ./postgres/data:/var/lib/postgresql/data
        env_file:
            - ./postgres/.env
        ports:
            - ${POSTGRES_PORT}:5432

    weather_logger:
        build: ./weather_logger
        depends_on:
            - postgres
        volumes:
          - ./log/weather_logger:/var/log/cron
